version: 2.1

workflows:
  version: 2
  build-test-and-maybe-deploy:
    jobs:
      - java-hello-world
      - java-second-hello-world:
          requires:
            - java-hello-world
      - csharp-hello-world
      - csharp-second-hello-world:
          requires:
            - csharp-hello-world
      - go-hello-world
      - go-second-hello-world:
          requires:
            - go-hello-world


commands:
  deploy-project:
    description: "Deploy the specified project"
    parameters:
      project:
        type: string
      version:
        type: string
    steps:
      - run:
          name: Deploy
          command: |
             cd <<parameters.project>>

             # Rather than triggering off tag pushes, we inspect for whether HEAD of release branches are tagged
             BASE_VERSION=$(<<parameters.version>>)
             VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`

             if [[ "${CIRCLE_BRANCH}" =~ release-.* && "${VERSION_SUFFIX}" != "alpha" ]]; then
               mkdir -p ~/.ssh
               echo "Adding github.com as known host."
               echo $GITHUB_PUBLIC_KEY >> ~/.ssh/known_hosts
               echo "Setting private SSH key."
               echo $GITHUB_COMMIT_KEY | base64 --decode >> ~/.ssh/id_rsa_git
               chmod 400 ~/.ssh/id_rsa_git # prevents "UNPROTECTED PRIVATE KEY FILE" error
               ./scripts/release_prod.sh
             else
               echo "Not releasable build, skipping deployment step"
             fi

jobs:
  java-hello-world:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-maven-{{ .Branch }}-{{ .BuildNum }}
            - v1-maven-{{ .Branch }}-
            - v1-maven-
      - run:
          name: Build
          command: |
            cd java/HelloWorld
            ./scripts/clean.sh
            ./scripts/build.sh
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: java/HelloWorld
          version: mvn -q -DforceStdout help:evaluate -Dexpression=project.version
  java-second-hello-world:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-maven-{{ .Branch }}-{{ .BuildNum }}
            - v1-maven-{{ .Branch }}-
            - v1-maven-
      - run:
          name: Build
          command: |

            cd java/SecondHelloWorld
            ./scripts/clean.sh
            ./scripts/build.sh
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: java/SecondHelloWorld
          version: mvn -q -DforceStdout help:evaluate -Dexpression=project.version
  csharp-hello-world:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
        environment:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-nuget-{{ .Branch }}-{{ .BuildNum }}
            - v1-nuget-{{ .Branch }}-
            - v1-nuget-
      - run:
          name: Setup csharp environment
          command: |
            apt-get update
            apt-get install -y libxml2-utils
            dotnet tool install -g trx2junit
            dotnet tool install -g dotnet-setversion
      - run:
          name: Build
          command: |
            cd csharp/HelloWorld
            ./scripts/clean.sh
            ./scripts/build.sh
      - save_cache:
          paths:
            - ~/.nuget
          key: v1-nuget-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: csharp/HelloWorld
          version: xmllint --xpath "//Project/PropertyGroup/Version/text()" Directory.Build.props
  csharp-second-hello-world:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
        environment:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - v1-nuget-{{ .Branch }}-{{ .BuildNum }}
            - v1-nuget-{{ .Branch }}-
            - v1-nuget-
      - run:
          name: Setup csharp environment
          command: |
            apt-get update
            apt-get install -y libxml2-utils
            dotnet tool install -g trx2junit
            dotnet tool install -g dotnet-setversion
      - run:
          name: Build
          command: |
            cd csharp/SecondHelloWorld
            ./scripts/clean.sh
            ./scripts/build.sh
      - save_cache:
          paths:
            - ~/.nuget
          key: v1-nuget-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: csharp/HelloWorld
          version: xmllint --xpath "//Project/PropertyGroup/Version/text()" Directory.Build.props
  go-hello-world:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - go-mod-v4-{{ .Branch }}-{{ .BuildNum }}
            - go-mod-v4-{{ .Branch }}-
            - go-mod-v4-
      - run:
          name: Build
          command: |
            cd go/HelloWorld
            ./scripts/build.sh
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-v4-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: go/HelloWorld
          version: cat .versionfile
  go-second-hello-world:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - restore_cache:
          keys:
            # when project files change, use increasingly general patterns to restore cache.
            # vN prefix in case we ever need to regenerate all caches
            - go-mod-v4-{{ .Branch }}-{{ .BuildNum }}
            - go-mod-v4-{{ .Branch }}-
            - go-mod-v4-
      - run:
          name: Build
          command: |
            cd go/SecondHelloWorld
            ./scripts/build.sh
      - save_cache:
          paths:
            - /go/pkg/mod
          key: go-mod-v4-{{ .Branch }}-{{ .BuildNum }}
      - deploy-project:
          project: go/SecondHelloWorld
          version: cat .versionfile
