name: Publish package to the Maven Central Repository
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events to branches matching refs/heads/releases/10
      - 'release-**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Set up C#
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: '3.1.x'
      - name: Set up Go 1.15
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: '1.15'
      - name: Publish package
        run: |
          cd java/HelloWorld
          BASE_VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          ARTIFACT_NAME=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.artifactId)
          TAG=`echo java/${ARTIFACT_NAME}/v${BASE_VERSION}`
          BRANCH=`echo ${GITHUB_REF##*/}`
          echo ${BASE_VERSION}
          echo {VERSION_SUFFIX}
          echo {ARTIFACT_NAME}
          echo ${TAG}
          echo ${BRANCH}
          if [[ "${BRANCH}" =~ release-.* && "${VERSION_SUFFIX}" != "alpha" ]]; then
            mvn -DskipTests deploy -Prelease
            git tag -f ${TAG} ${GITHUB_SHA}
            git push origin --tags
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
