name: Publish package to the Maven Central Repository
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events to branches matching refs/heads/releases/10
      - 'release-**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Set up C#
        uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439
        with:
          dotnet-version: '3.1.x'
      - name: Set up Go 1.15
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: '1.15'
      - name: Publish Java HelloWorld
        run: |
          cd java/HelloWorld
          BASE_VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Java SecondHelloWorld
        run: |
          cd java/SecondHelloWorld
          BASE_VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish C# HelloWorld
        run: |
          cd csharp/HelloWorld
          sudo apt-get update -y
          sudo apt-get install -y libxml2-utils
          dotnet tool install -g trx2junit
          dotnet tool install -g dotnet-setversion
          BASE_VERSION=$(xmllint --xpath "//Project/PropertyGroup/Version/text()" Directory.Build.props)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish C# SecondHelloWorld
        run: |
          cd csharp/SecondHelloWorld
          BASE_VERSION=$(xmllint --xpath "//Project/PropertyGroup/Version/text()" Directory.Build.props)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Go HelloWorld
        run: |
          cd go/HelloWorld
          BASE_VERSION=$(cat .versionfile)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish C# SecondHelloWorld
        run: |
          cd go/SecondHelloWorld
          BASE_VERSION=$(cat .versionfile)
          VERSION_SUFFIX=`echo ${BASE_VERSION} | cut -f2 -d'-'`
          if [[ "${VERSION_SUFFIX}" != "alpha" ]]; then
            ./scripts/release_prod.sh
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

